server:
  port: 8001

mybatis:
  configlocation: classpath:mybatis/mybatis.cfg.xml #Mybatis配置文件所在路径
  type-aliases-package: com.microservice.bean   #所有bean别名所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  application:
    name: microservice-dept            #对外暴露的微服务名字
  datasource:                         #数据库连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&amp;useSSL=false
    username: root
    password: root
      #druid连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


eureka:
  instance:
    instance-id: microservice-dept8001-hystrix #默认名称修改
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    register-with-eureka: true #是否注册
    fetch-registry: true
    service-url:
     # 集群:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

     # 单机
     # defaultZone: http://localhost:7001/eureka/  # 注册中心访问地址

#Info信息显示
info:
  app.name: microservice
  companny.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#springboot2.x 需要添加以下才能访问/actuator/hystrix.stream和actuator/health;否则会报404
management:
  endpoints:
    web:
      exposure:
        include: '*'
#springboot2.x 需要添加以下才能访问/actuator/hystrix.stream和actuator/health;否则会报404
